<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DemoApp.Application\DemoApp.Application.csproj" />
    <ProjectReference Include="..\..\..\src\EricksonLopez.Pagination.EntityFrameworkCore\EricksonLopez.Pagination.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\src\EricksonLopez.Pagination.Dapper\EricksonLopez.Pagination.Dapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper.StrongName" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>


