<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1701;CS0618;CA1000;CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing" />
    <PackageReference Include="Microsoft.CodeAnalysis.Testing.Verifiers.XUnit" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Update="xunit" VersionOverride="2.4.2" />
    <PackageReference Update="xunit.runner.visualstudio" VersionOverride="2.4.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Pagination.Analyzers\EricksonLopez.Pagination.Analyzers.csproj" />
  </ItemGroup>

</Project>


