<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1903;NU1603;CS0618;CA1008;CA1031;CA1062</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="linq2db.SQLite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="linq2db.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Pagination.LinqToDB\EricksonLopez.Pagination.LinqToDB.csproj" />
  </ItemGroup>
</Project>

