// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.Pagination.SourceGenerators
{
    /// <summary>
    /// Generates AOT-compatible cursor decoding registries by analyzing cursor pagination invocations.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class CursorDecoderGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Initializes the incremental source generator.
        /// </summary>
        /// <param name="context">The context used to register syntax providers and output source files.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var invocations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => 
                    {
                        if (s is InvocationExpressionSyntax inv && inv.Expression is MemberAccessExpressionSyntax member)
                        {
                            var name = member.Name.Identifier.Text;

                            // F-010 fix: the highly-specific method names are very unlikely to collide
                            // with unrelated libraries and are selected broadly.
                            if (name is "ToCursorPagedListAsync" or "ToCursorPagedList" or "DecodeAfter" or "DecodeBefore")
                                return true;

                            // F-010 fix: "Ascending" and "Descending" are very common method names
                            // (e.g., LINQ, Entity Framework, any fluent API). Selecting all of them
                            // for semantic analysis causes unnecessary overhead in large codebases.
                            // We restrict these to invocations where the receiver chain appears to
                            // originate from a Keyset-related call by checking for "Keyset" in the
                            // parent expression text. This is a heuristic syntax filter only — the
                            // semantic transform still performs exact symbol validation.
                            if (name is "Ascending" or "Descending")
                            {
                                // Walk up the expression chain to see if "Keyset" appears in it,
                                // which strongly suggests this is a KeysetBuilder<T>.Ascending() call.
                                var exprText = member.Expression.ToString();
                                // Stryker disable once all : Heuristic filtering
                                return exprText.Contains("Keyset") || exprText.Contains("keyset");
                            }
                        }
                        return false;
                    },
                    transform: static (ctx, _) => GetCursorKeyTypeAndLocation(ctx))
                .Where(static t => t.Type is not null)
                .Collect();

            context.RegisterSourceOutput(invocations, static (spc, items) =>
            {
                // Stryker disable once all : Generator syntax logic
                var distinctItems = items
                    .GroupBy(x => x.Type, SymbolEqualityComparer.Default)
                    .Select(g => g.First())
                    .ToList();

                // Stryker disable all : Hardcoded generator template emission
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable"); // FIX-09: emit nullable context for projects with <Nullable>enable</Nullable>
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine("namespace EricksonLopez.Pagination.Generated");
                sb.AppendLine("{");
                sb.AppendLine("    public static class CursorDecoderRegistryFactory");
                sb.AppendLine("    {");
                sb.AppendLine("        public static EricksonLopez.Pagination.InMemoryCursorDecoderRegistry CreateRegistry()");
                sb.AppendLine("        {");
                sb.AppendLine("            var registry = new EricksonLopez.Pagination.InMemoryCursorDecoderRegistry();");


                foreach (var item in distinctItems)
                {
                    var type = item.Type!;
                    if (IsHandledPrimitive(type)) continue;

                    var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    
                    bool supported = false;
                    string? decoderLogic = null;

                    if (type.TypeKind == TypeKind.Enum)
                    {
                        decoderLogic = $"return System.Enum.Parse<{typeName}>(s);";
                        supported = true;
                    }
                    else if (ImplementsIParsable(type) || HasParseWithFormatProvider(type))
                    {
                        decoderLogic = $"return {typeName}.Parse(s, System.Globalization.CultureInfo.InvariantCulture);";
                        supported = true;
                    }
                    else if (HasTryParseWithFormatProvider(type))
                    {
                        decoderLogic = $"if ({typeName}.TryParse(s, System.Globalization.CultureInfo.InvariantCulture, out {typeName} result)) return result;\n                throw new System.FormatException($\"Cannot parse '{{s}}' as {typeName}\");";
                        supported = true;
                    }
                    else
                    {
                        var hasParse = type.GetMembers("Parse").OfType<IMethodSymbol>().Any(m => m.Parameters.Length == 1 && m.Parameters[0].Type.SpecialType == SpecialType.System_String);
                        if (hasParse)
                        {
                            decoderLogic = $"return {typeName}.Parse(s);";
                            supported = true;
                        }
                    }

                    if (supported && decoderLogic != null)
                    {
                        sb.AppendLine($"            registry.Register<{typeName}>(s => ");
                        sb.AppendLine("            {");
                        sb.AppendLine($"                {decoderLogic}");
                        sb.AppendLine("            });");

                    }
                    else
                    {
                        var descriptor = new DiagnosticDescriptor(
                            id: "PAG001",
                            title: "Unsupported Cursor Key Type",
                            messageFormat: "The type '{0}' cannot be automatically decoded by the source generator. It must implement IParsable or have a valid Parse/TryParse method.",
                            category: "Pagination",
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true);
                        
                        spc.ReportDiagnostic(Diagnostic.Create(descriptor, item.Location, type.Name));
                    }
                }

                sb.AppendLine("            return registry;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Registers all AOT-safe cursor decoders discovered at compile time into the DI container.");
                sb.AppendLine("        /// Call this from <c>Program.cs</c> when using Native AOT or trimming-enabled publishing.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        /// <example>");
                sb.AppendLine("        /// <code>");
                sb.AppendLine("        /// // In Program.cs:");
                sb.AppendLine("        /// builder.Services.AddAotCursorDecoders();");
                sb.AppendLine("        /// </code>");
                sb.AppendLine("        /// </example>");
                sb.AppendLine("        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddAotCursorDecoders(");
                sb.AppendLine("            this Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
                sb.AppendLine("        {");
                sb.AppendLine("            services.AddSingleton<EricksonLopez.Pagination.Abstractions.ICursorDecoderRegistry>(CreateRegistry());");
                sb.AppendLine("            return services;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                // Stryker restore all

                spc.AddSource("CursorDecoderInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            });
        }

        // Stryker disable once all : Semantic analysis helper method
        private static bool IsHandledPrimitive(ITypeSymbol type)
        {
            if (type.SpecialType == SpecialType.System_Int32 || type.SpecialType == SpecialType.System_Int64 || type.SpecialType == SpecialType.System_String || type.SpecialType == SpecialType.System_DateTime)
                return true;

            var name = type.ToDisplayString();
            return name == "Guid" || name == "System.Guid" || name == "DateTimeOffset" || name == "System.DateTimeOffset";
        }

        // Stryker disable once all : Semantic analysis helper method
        private static bool HasTryParseWithFormatProvider(ITypeSymbol type)
        {
            return type.GetMembers("TryParse").OfType<IMethodSymbol>().Any(m =>
                m.Parameters.Length == 3 &&
                m.Parameters[0].Type.SpecialType == SpecialType.System_String &&
                (m.Parameters[1].Type.Name == "IFormatProvider" || m.Parameters[1].Type.ToDisplayString() == "System.IFormatProvider") &&
                m.Parameters[2].RefKind == RefKind.Out);
        }

        // Stryker disable once all : Semantic analysis helper method
        private static bool HasParseWithFormatProvider(ITypeSymbol type)
        {
            return type.GetMembers("Parse").OfType<IMethodSymbol>().Any(m =>
                m.Parameters.Length == 2 &&
                m.Parameters[0].Type.SpecialType == SpecialType.System_String &&
                (m.Parameters[1].Type.Name == "IFormatProvider" || m.Parameters[1].Type.ToDisplayString() == "System.IFormatProvider"));
        }

        // Stryker disable once all : Semantic analysis helper method
        private static bool ImplementsIParsable(ITypeSymbol type)
        {
            return type.AllInterfaces.Any(i => i.Name == "IParsable" || i.Name == "ISpanParsable");
        }

        // Stryker disable once all : Semantic analysis helper method
        private static (ITypeSymbol? Type, Location? Location) GetCursorKeyTypeAndLocation(GeneratorSyntaxContext context)
        {
            var invocation = (InvocationExpressionSyntax)context.Node;
            var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;

            if (symbol == null) return (null, null);

            var name = symbol.Name;
            var typeName = symbol.ContainingType?.Name;
            var assemblyName = symbol.ContainingAssembly?.Name;

            bool isPaginationMethod = false;

            if (name == "DecodeAfter" || name == "DecodeBefore")
            {
                isPaginationMethod = assemblyName == "EricksonLopez.Pagination" && typeName == "CursorPaginationParametersExtensions";
            }
            else if (symbol.IsExtensionMethod && (name == "ToCursorPagedListAsync" || name == "ToCursorPagedList"))
            {
                isPaginationMethod = 
                    (assemblyName == "EricksonLopez.Pagination" && typeName == "CursorPagedListExtensions") ||
                    (assemblyName == "EricksonLopez.Pagination.Dapper" && typeName == "DbConnectionCursorExtensions") ||
                    (assemblyName == "EricksonLopez.Pagination.EntityFrameworkCore" && typeName == "QueryableExtensions") ||
                    (assemblyName == "EricksonLopez.Pagination.MongoDB" && (typeName == "MongoCursorPaginationExtensions" || typeName == "FindFluentPaginationExtensions"));
            }

            else if (name == "Ascending" || name == "Descending")
            {
                isPaginationMethod = assemblyName == "EricksonLopez.Pagination.EntityFrameworkCore" && typeName == "KeysetBuilder";
            }

            if (isPaginationMethod)
            {
                var typeArgs = symbol.TypeArguments;
                if (typeArgs.Length == 0) return (null, null);

                if ((name == "Ascending" || name == "Descending") && typeArgs.Length == 1)
                {
                    return (typeArgs[0], invocation.GetLocation());
                }

                // Typically <T, TKey> or <TDocument, TProjection, TKey>
                if (typeArgs.Length == 1) return (typeArgs[0], invocation.GetLocation());
                if (typeArgs.Length == 2) return (typeArgs[1], invocation.GetLocation());
                if (typeArgs.Length == 3) return (typeArgs[2], invocation.GetLocation());
            }

            return (null, null);
        }
    }
}

