// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.Pagination.SourceGenerators
{
    /// <summary>
    /// Generates strongly typed filter provider implementations for classes decorated with <c>[GenerateFilterProvider]</c>.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public class FilterProviderGenerator : IIncrementalGenerator
    {
        private const string AttributeName = "EricksonLopez.Pagination.Abstractions.GenerateFilterProviderAttribute";
        private const string ShortAttributeName = "GenerateFilterProvider";

        /// <summary>
        /// Initializes the incremental source generator.
        /// </summary>
        /// <param name="context">The context used to register syntax providers and output source files.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var targets = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsCandidate(s),
                    transform: static (ctx, _) => GetSemanticTarget(ctx))
                .Where(static m => m is not null)
                .Collect();

            context.RegisterSourceOutput(targets, static (spc, types) =>
            {
                var distinctTypes = types
                    .Where(t => t != null)
                    .GroupBy(t => t, SymbolEqualityComparer.Default)
                    .Select(g => (INamedTypeSymbol)g.Key!)
                    .ToList();

                foreach (var type in distinctTypes)
                {
                    var source = GenerateFilterProviderSource(type);
                    var nsPrefix = type.ContainingNamespace.IsGlobalNamespace ? "" : $"{type.ContainingNamespace.ToDisplayString().Replace('.', '_')}_";
                    var hintName = $"{nsPrefix}{type.Name}_FilterProvider.g.cs";
                    spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            // Stryker disable once all : Optimization for empty attribute list
            if (node is TypeDeclarationSyntax typeDecl && typeDecl.AttributeLists.Count > 0)
            {
                foreach (var attrList in typeDecl.AttributeLists)
                {
                    foreach (var attr in attrList.Attributes)
                    {
                        var name = attr.Name.ToString();
                        if (name is ShortAttributeName or "GenerateFilterProviderAttribute" or AttributeName)
                            return true;
                    }
                }
            }
            // Stryker disable once all : Syntax filter fallback
            return false;
        }

        private static INamedTypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
        {
            if (context.Node is not TypeDeclarationSyntax typeDecl) return null;

            var symbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
            if (symbol == null) return null;

            foreach (var attr in symbol.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == AttributeName)
                    return symbol;
            }

            return null;
        }

        // Stryker disable all : Source generation template emission
        private static string GenerateFilterProviderSource(INamedTypeSymbol typeSymbol)
        {
            var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? "EricksonLopez.Pagination.Generated"
                : $"{typeSymbol.ContainingNamespace.ToDisplayString()}.Generated";

            var typeName = typeSymbol.Name;
            var fullTypeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var providerClassName = $"{typeName}FilterProvider";

            var properties = typeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod != null)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.Linq.Expressions;");
            sb.AppendLine("using EricksonLopez.Pagination.Abstractions;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// AOT-safe, compile-time filter provider for <see cref=\"{fullTypeName}\"/>.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public sealed class {providerClassName} : IFilterProvider<{fullTypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Gets the shared singleton instance of <see cref=\"{providerClassName}\"/>.</summary>");
            sb.AppendLine($"        public static {providerClassName} Instance {{ get; }} = new();");
            sb.AppendLine();
            sb.AppendLine($"        /// <inheritdoc/>");
            sb.AppendLine($"        public Expression<Func<{fullTypeName}, bool>>? Build(FilterParameters filter)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (!filter.HasValue) return null;");
            sb.AppendLine();
            sb.AppendLine("            Expression<Func<" + fullTypeName + ", bool>>? result = null;");
            sb.AppendLine("            var rawValue = filter.Value!;");
            sb.AppendLine("            var clauses = rawValue.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);");
            sb.AppendLine();
            sb.AppendLine("            foreach (var clause in clauses)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (string.IsNullOrWhiteSpace(clause)) continue;");
            sb.AppendLine();
            sb.AppendLine("                var expr = BuildClauseExpression(clause);");
            sb.AppendLine("                if (expr != null)");
            sb.AppendLine("                {");
            sb.AppendLine("                    result = result == null ? expr : result.And(expr);");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        private static Expression<Func<{fullTypeName}, bool>>? BuildClauseExpression(string clause)");
            sb.AppendLine("        {");
            sb.AppendLine("            string op;");
            sb.AppendLine("            int opIdx = -1;");
            sb.AppendLine();
            sb.AppendLine("            // 2-character operators");
            sb.AppendLine("            if ((opIdx = clause.IndexOf(\"!=\", StringComparison.Ordinal)) >= 0) op = \"!=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf(\">=\", StringComparison.Ordinal)) >= 0) op = \">=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf(\"<=\", StringComparison.Ordinal)) >= 0) op = \"<=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf(\"~=\", StringComparison.Ordinal)) >= 0) op = \"~=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf(\"^=\", StringComparison.Ordinal)) >= 0) op = \"^=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf(\"$=\", StringComparison.Ordinal)) >= 0) op = \"$=\";");
            sb.AppendLine("            // 1-character operators");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf('=')) >= 0) op = \"=\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf('>')) >= 0) op = \">\";");
            sb.AppendLine("            else if ((opIdx = clause.IndexOf('<')) >= 0) op = \"<\";");
            sb.AppendLine("            else return null;");
            sb.AppendLine();
            sb.AppendLine("            var fieldName = clause.Substring(0, opIdx).Trim();");
            sb.AppendLine("            var valueStr = clause.Substring(opIdx + op.Length).Trim();");
            sb.AppendLine();

            foreach (var prop in properties)
            {
                var propName = prop.Name;
                var propType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var isString = prop.Type.SpecialType == SpecialType.System_String;
                var isInt = prop.Type.SpecialType == SpecialType.System_Int32;
                var isLong = prop.Type.SpecialType == SpecialType.System_Int64;
                var isDouble = prop.Type.SpecialType == SpecialType.System_Double;
                var isDecimal = prop.Type.SpecialType == SpecialType.System_Decimal;
                var isBool = prop.Type.SpecialType == SpecialType.System_Boolean;
                var isGuid = propType is "global::System.Guid" or "global::Guid";
                var isDateTime = propType is "global::System.DateTime" or "global::DateTime";
                var isDateTimeOffset = propType is "global::System.DateTimeOffset" or "global::DateTimeOffset";

                sb.AppendLine($"            if (string.Equals(fieldName, \"{propName}\", StringComparison.OrdinalIgnoreCase))");
                sb.AppendLine("            {");

                if (isString)
                {
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == valueStr;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != valueStr;");
                    sb.AppendLine($"                    case \"~=\": return x => x.{propName} != null && x.{propName}.Contains(valueStr);");
                    sb.AppendLine($"                    case \"^=\": return x => x.{propName} != null && x.{propName}.StartsWith(valueStr);");
                    sb.AppendLine($"                    case \"$=\": return x => x.{propName} != null && x.{propName}.EndsWith(valueStr);");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isInt)
                {
                    sb.AppendLine("                if (!int.TryParse(valueStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isLong)
                {
                    sb.AppendLine("                if (!long.TryParse(valueStr, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isDouble)
                {
                    sb.AppendLine("                if (!double.TryParse(valueStr, NumberStyles.Float, CultureInfo.InvariantCulture, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isDecimal)
                {
                    sb.AppendLine("                if (!decimal.TryParse(valueStr, NumberStyles.Number, CultureInfo.InvariantCulture, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isBool)
                {
                    sb.AppendLine("                if (!bool.TryParse(valueStr, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isGuid)
                {
                    sb.AppendLine("                if (!Guid.TryParse(valueStr, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isDateTimeOffset)
                {
                    sb.AppendLine("                if (!DateTimeOffset.TryParse(valueStr, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }
                else if (isDateTime)
                {
                    sb.AppendLine("                if (!DateTime.TryParse(valueStr, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind, out var v)) return null;");
                    sb.AppendLine("                switch (op)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    case \"=\": return x => x.{propName} == v;");
                    sb.AppendLine($"                    case \"!=\": return x => x.{propName} != v;");
                    sb.AppendLine($"                    case \">\": return x => x.{propName} > v;");
                    sb.AppendLine($"                    case \">=\": return x => x.{propName} >= v;");
                    sb.AppendLine($"                    case \"<\": return x => x.{propName} < v;");
                    sb.AppendLine($"                    case \"<=\": return x => x.{propName} <= v;");
                    sb.AppendLine("                    default: return null;");
                    sb.AppendLine("                }");
                }

                sb.AppendLine("            }");
            }

            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            // Stryker restore all

            return sb.ToString();
        }
    }
}



