<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Pagination.Cosmos\EricksonLopez.Pagination.Cosmos.csproj" />
  </ItemGroup>

</Project>


