// Copyright © Erickson Lopez. MIT License.
namespace EricksonLopez.Pagination.SourceGenerators.Tests;

public static class GeneratorTestSnippets
{
    public const string ExpectedEmptyRegistry = @"// <auto-generated/>
#nullable enable
using System;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;

namespace EricksonLopez.Pagination.Generated
{
    public static class CursorDecoderRegistryFactory
    {
        public static EricksonLopez.Pagination.InMemoryCursorDecoderRegistry CreateRegistry()
        {
            var registry = new EricksonLopez.Pagination.InMemoryCursorDecoderRegistry();
            return registry;
        }

        /// <summary>
        /// Registers all AOT-safe cursor decoders discovered at compile time into the DI container.
        /// Call this from <c>Program.cs</c> when using Native AOT or trimming-enabled publishing.
        /// </summary>
        /// <example>
        /// <code>
        /// // In Program.cs:
        /// builder.Services.AddAotCursorDecoders();
        /// </code>
        /// </example>
        public static Microsoft.Extensions.DependencyInjection.IServiceCollection AddAotCursorDecoders(
            this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            services.AddSingleton<EricksonLopez.Pagination.Abstractions.ICursorDecoderRegistry>(CreateRegistry());
            return services;
        }
    }
}
";

    public const string DummySource = @"
            namespace Microsoft.Extensions.DependencyInjection 
            { 
                public interface IServiceCollection 
                {
                    IServiceCollection TryAddSingleton<TService>(object implementationInstance);
                }
                public static class ServiceCollectionServiceExtensions
                {
                    public static IServiceCollection AddSingleton<TService>(this IServiceCollection services, TService implementationInstance)
                        where TService : class
                        => services;
                }
            }
            namespace EricksonLopez.Pagination 
            { 
                public class InMemoryCursorDecoderRegistry : EricksonLopez.Pagination.Abstractions.ICursorDecoderRegistry
                {
                    public void Register<T>(System.Func<string, T> a) {}
                }
            }
            namespace EricksonLopez.Pagination.Abstractions 
            { 
                public interface ICursorDecoderRegistry {} 
            }
        ";

    public const string Generator_WithoutPaginationInvocations_DoesNotGenerateSource_Source = @"
        namespace Test
        {
            public class Program
            {
                public static void Main() { new object().ToString(); }
            }
        }";

    public const string Generator_WithPrimitiveTypeInvocation_DoesNotGenerateRegistration_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int>();
                }
            }
        }";

    public const string Generator_WithCustomType_GeneratesRegistrationAndTryParse_Source = @"

        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;

            public class MyCustomType 
            {
                public static bool TryParse(string s, System.IFormatProvider? provider, out MyCustomType result) 
                {
                    result = new MyCustomType();
                    return true;
                }
            }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<MyCustomType>();
                }
            }
        }";

    public const string Generator_WithCustomTypeWithoutTryParse_GeneratesRegistrationWithConvert_Source = @"
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;

            public class MyCustomType2 
            {
            }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<MyCustomType2>();
                }
            }
        }";

    public const string Generator_TargetMethodNamesAndAssembliesAreMatched_Source = @"
        namespace EricksonLopez.Pagination.Dapper {
            public static class DbConnectionCursorExtensions {
                public static void ToCursorPagedListAsync<T1, TCursor>(this object o) {}
            }
        }
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.Dapper;
            using EricksonLopez.Pagination;

            public class DapperType { public static DapperType Parse(string s, System.IFormatProvider p) => new(); }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int, DapperType>();
                }
            }
        }";

    public const string Generator_DecodeAfterAndBefore_AreMatched_Source = @"
        namespace EricksonLopez.Pagination {
            public class CursorPaginationParameters { public string? After; public string? Before; }
            public interface ICursorEncoder {}
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
            public static class CursorPaginationParametersExtensions {
                public static TCursor? DecodeAfter<TCursor>(this CursorPaginationParameters parameters, ICursorEncoder? cursorEncoder = null) => default;
                public static TCursor? DecodeBefore<TCursor>(this CursorPaginationParameters parameters, ICursorEncoder? cursorEncoder = null) => default;
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination;

            public class AfterType { public static AfterType Parse(string s, System.IFormatProvider p) => new(); }
            public class BeforeType { public static BeforeType Parse(string s, System.IFormatProvider p) => new(); }

            public class Program
            {
                public static void Main() 
                { 
                    var p = new CursorPaginationParameters();
                    p.DecodeAfter<AfterType>();
                    p.DecodeBefore<BeforeType>();
                }
            }
        }";

    public const string Generator_WithParseMethod_GeneratesRegistrationWithParse_Source = @"
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
            public static class CursorPagedListExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination;

            public class TypeWithParse 
            {
                public static TypeWithParse Parse(string s, System.IFormatProvider? provider) 
                {
                    return new TypeWithParse();
                }
            }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<TypeWithParse>();
                }
            }
        }";

    public const string Generator_WithIParsable_GeneratesRegistrationWithParse_Source = @"
        namespace System {
            public interface IParsable<TSelf> where TSelf : IParsable<TSelf> { }
        }
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
            public static class CursorPagedListExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination;

            public class ParsableType : System.IParsable<ParsableType>
            {
                public static ParsableType Parse(string s, System.IFormatProvider? provider) 
                {
                    return new ParsableType();
                }
            }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<ParsableType>();
                }
            }
        }";

    public const string Generator_TargetAssembliesAreMatched_MongoDB_Source = @"
        namespace EricksonLopez.Pagination.MongoDB {
            public static class FindFluentPaginationExtensions {
                public static void ToCursorPagedListAsync<T1, T2, TCursor>(this object o) {}
            }
        }
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderRegistry {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.MongoDB;

            public class MongoType { public static MongoType Parse(string s, System.IFormatProvider p) => new(); }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int, string, MongoType>();
                }
            }
        }";

    public const string Generator_WithPrimitiveTypeInvocations_DoesNotGenerateRegistration_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int>();
                    new object().ToCursorPagedListAsync<long>();
                    new object().ToCursorPagedListAsync<System.Guid>();
                    new object().ToCursorPagedListAsync<System.DateTimeOffset>();
                    new object().ToCursorPagedListAsync<System.DateTime>();
                    new object().ToCursorPagedListAsync<string>();
                }
            }
        }";

    public const string Generator_WithEnumType_GeneratesRegistrationWithEnumParse_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public enum MyEnum { A, B }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<MyEnum>();
                }
            }
        }";

    public const string Generator_WithParseStringOnly_GeneratesRegistrationWithParseString_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class MyParseType {
                public static MyParseType Parse(string s) => new();
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<MyParseType>();
                }
            }
        }";

    public const string Generator_WithKeysetBuilderAscending_GeneratesRegistration_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public class KeysetBuilder<T> {
                public KeysetBuilder<T> Ascending<TKey>(System.Linq.Expressions.Expression<System.Func<T, TKey>> expr) => this;
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class AscType { public static AscType Parse(string s, System.IFormatProvider p) => new(); }
            public class Entity { public AscType Value { get; set; } }
            public class Program
            {
                public static void Main() 
                { 
                    new KeysetBuilder<Entity>().Ascending(x => x.Value);
                }
            }
        }";

    public const string Generator_WithKeysetBuilderDescending_GeneratesRegistration_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public class KeysetBuilder<T> {
                public KeysetBuilder<T> Descending<TKey>(System.Linq.Expressions.Expression<System.Func<T, TKey>> expr) => this;
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class DescType { public static DescType Parse(string s, System.IFormatProvider p) => new(); }
            public class Entity { public DescType Value { get; set; } }
            public class Program
            {
                public static void Main() 
                { 
                    new KeysetBuilder<Entity>().Descending(x => x.Value);
                }
            }
        }";

    public const string Generator_ToCursorPagedList_IsMatched_Source = @"
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderServiceCollectionExtensions {
                public static void Register<T>(System.Func<string, T> d) {}
            }
            public static class CursorPagedListExtensions {
                public static void ToCursorPagedList<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination;
            public class SyncType { public static SyncType Parse(string s, System.IFormatProvider p) => new(); }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedList<SyncType>();
                }
            }
        }";

    public const string Generator_TargetAssembliesAreMatched_MongoCursor_Source = @"
        namespace EricksonLopez.Pagination.MongoDB {
            public static class MongoCursorPaginationExtensions {
                public static void ToCursorPagedListAsync<T1, TCursor>(this object o) {}
            }
        }
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderRegistry {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.MongoDB;

            public class MongoCursorType { public static MongoCursorType Parse(string s, System.IFormatProvider p) => new(); }

            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int, MongoCursorType>();
                }
            }
        }";

    public const string Generator_WithFourTypeArguments_DoesNotThrow_Source = @"
        namespace EricksonLopez.Pagination.MongoDB {
            public static class MongoCursorPaginationExtensions {
                public static void ToCursorPagedListAsync<T1, T2, T3, T4>(this object o) {}
            }
        }
        namespace EricksonLopez.Pagination {
            public static class CursorDecoderRegistry {
                public static void Register<T>(System.Func<string, T> d) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.MongoDB;
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<int, string, string, string>();
                }
            }
        }";

    public const string Generator_WithFakePaginationMethod_DoesNotGenerate_Source = @"
        namespace EricksonLopez.Pagination.Fake {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
                public static void Ascending<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.Fake;
            public class CustomFakeType {}
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<CustomFakeType>();
                    new object().Ascending<CustomFakeType>();
                }
            }
        }";

    public const string Generator_WithTryParseInvalidSignature_DoesNotGenerateTryParse_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class TryParseFakeType 
            {
                // Missing out param
                public static bool TryParse(string s, System.IFormatProvider? provider, TryParseFakeType result) => false;
            }
            public class TryParseFakeType2
            {
                // Wrong type for provider
                public static bool TryParse(string s, int notProvider, out TryParseFakeType2 result) { result = new(); return true; }
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<TryParseFakeType>();
                    new object().ToCursorPagedListAsync<TryParseFakeType2>();
                }
            }
        }";

    public const string Generator_WithParseInvalidSignature_DoesNotGenerateParse_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class ParseFakeType 
            {
                // Takes int instead of string
                public static ParseFakeType Parse(int s, System.IFormatProvider? provider) => new();
            }
            public class ParseFakeType2 
            {
                // Wrong provider type
                public static ParseFakeType2 Parse(string s, int notProvider) => new();
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<ParseFakeType>();
                    new object().ToCursorPagedListAsync<ParseFakeType2>();
                }
            }
        }";

    public const string Generator_WithISpanParsable_GeneratesParse_Source = @"
        namespace System {
            public interface ISpanParsable<TSelf> { }
        }
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class SpanParsableType : System.ISpanParsable<SpanParsableType>
            {
                public static SpanParsableType Parse(string s, System.IFormatProvider? provider) => new();
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<SpanParsableType>();
                }
            }
        }";

    public const string Generator_WithIParsable_GeneratesParse_Source = @"
        namespace System {
            public interface IParsable<TSelf> { }
        }
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class ParsableType : System.IParsable<ParsableType>
            {
                public static ParsableType Parse(string s, System.IFormatProvider? provider) => new();
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<ParsableType>();
                }
            }
        }";

    public const string Generator_WithFormatProviderParseOnly_GeneratesParse_Source = @"
        namespace EricksonLopez.Pagination.EntityFrameworkCore {
            public static class QueryableExtensions {
                public static void ToCursorPagedListAsync<T>(this object o) {}
            }
        }
        namespace Test
        {
            using EricksonLopez.Pagination.EntityFrameworkCore;
            public class FormatProviderParseType
            {
                public static FormatProviderParseType Parse(string s, System.IFormatProvider? provider) => new();
            }
            public class Program
            {
                public static void Main() 
                { 
                    new object().ToCursorPagedListAsync<FormatProviderParseType>();
                }
            }
        }";
}
